### ISSUE TITLE
showing tag but not showing what the person is saying in 1.18.1

### ISSUE THREAD

**Issue by Rdoactvedragon** [chunkaligned/fabric-discord-integration#9]
Idk if i am doing something wrong with the IDs and stuff, but it only shows the tags when said in the discord chat and not what is said by said tags
![Right(3)](https://user-images.githubusercontent.com/97382305/203646297-f7c7f9f8-e5f8-446c-adde-644867cb7a75.png)
![Right(1)](https://user-images.githubusercontent.com/97382305/203646299-f143995a-3aa9-4053-9206-cd683c809342.png)
![Right(2)](https://user-images.githubusercontent.com/97382305/203646300-572b564b-21cf-44af-8317-b8c57d3c0af2.png)

**Comment by hkva** [comment]
Thanks for checking out the mod. I see the problem and am looking into it now

**Comment by hkva** [comment]
@Rdoactvedragon This seems to be caused by a new security feature on Discord's end. Enabling "Message Content Intent" for your discord bot should fix it.

![image](https://user-images.githubusercontent.com/91440203/203677112-a8f762ef-903e-44db-bcac-96f9d86f4e1b.png)

Let me know if this works. I'll add a note to the README telling future users to set this option.

**Comment by Rdoactvedragon** [comment]
alrighty thank you for telling me how to fix this.
